### ISSUE TITLE
Should Map have withDefault and withDefaultValue as in Scala

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#1194]
Or has this been studied already?

**Comment by danieldietrich** [comment]
Hi Martti,

I haven't considered it yet. Looking at the Scala source, there is one wrapper `WithDefault`. For Scala it is possible to have only one wrapper because the higher-kinded types allow to preserve the Map type when wrapping the actual Map instance. In Java this is not possible. We would need a wrapper for each Map implementation.

We need to further investigate, how an implementation could look like. We should target the following:

* Don't leak additional types (wrappers) as public API to the outside
* Minimize the number of additional types. Currently I see HashMap.WithDefault, LinkedHashMap.WithDefault, TreeMap.WithDefault, HashMultimap.WithDefault, LinkedHashMultimap.WithDefault, TreeMultimap.WithDefault. These are necessary because of the next point:
* This change should not affect the existing Map implementation in the way that additional instances are added if not asked for (i.e. if withDefault was not called).

**Comment by mvh77** [comment]
Yes you're right, it's a bit complex. Also the behaviour is not necessarily obvious since _some methods (get, contains, iterator, keys, etc) are not affected and invoking transformer methods (e.g. map) will not preserve the default value_. The only real advantage is you can transform a map from a partial function to a full function. This could be solved with a static method on Map that would return a wraper that only affects the apply method...

**Comment by danieldietrich** [comment]
Currently Map implements Function1 which throws if the key is not present:

```java
interface Map<K, V> extends Traversable<Tuple2<K, V>>, Function1<K, V> {
    @Override
    default V apply(K key) {
        return get(key).getOrElseThrow(NoSuchElementException::new);
    }
}
```

It would be better to reflect that a Map is a partial function by returning `Option<V>` instead of `V`:

```java
interface Map<K, V> extends Traversable<Tuple2<K, V>>, Function1<K, Option<V>> {
    @Override
    default Option<V> apply(K key) {
        return get(key);
    }
}
```

Then `withDefault` could just return a total function instead of a Map:

```java
interface Map<K, V> extends Traversable<Tuple2<K, V>>, Function1<K, Option<V>> {
    @Override
    default Function1<K, V> withDefault(V defaultValue) {
        return k -> get(key).getOrElse(defaultValue);
    }
}
```

(Is this signature right compared to Scala? There withDefault and withDefaultValue are distinguished...)

**Comment by mvh77** [comment]
Well, since we have get() that returns an Option, I wouldn't touch apply, and would have that throw just like it does currently and in Scala. Unless we want to change that everywhere, meaning for Seqs and Sets as well? Where else?

But your last example is what I also came up with, meaning just returning a Function1. We could have something similar to Scala signature wise:

```java
default Function1<K, V> withDefaultValue(V def) {
    return k -> get(k).getOrElse(def);
}

default Function1<K,V> withDefault(Function<? super K, ? extends V> def)  {
    return k -> get(k).getOrElse(() -> def.apply(k));
}
```

Would this make sense?

**Comment by mvh77** [comment]
Except that Sets of course are already full functions from T -> Boolean :smile:

**Comment by danieldietrich** [comment]
Yes, that looks good! We should add these two methods.

**Comment by mvh77** [comment]
Looking at Seq I'm a bit puzzled by the static lift method on Function1. Should we also have an instance method lift on maybe Seq and Map that returns an Option returning Function1? Map already has get():Option so it's redundant, but Scala has this too. Seq has no way to get an Option<T> from an index at this moment.

**Comment by danieldietrich** [comment]
Yes, we should consider it. I will take an in-depth look after the new web-page is online...

**Comment by danieldietrich** [comment]
May we close this ticket?

**Comment by texasbruce** [comment]
This is marked as deprecated. What is the reason?

**Comment by danieldietrich** [comment]
@texasbruce it is wrong, I will undeprecate it! 1.0.0 is on its way - soon!

**Comment by danieldietrich** [comment]
@texasbruce please take a look at #2590. It is not worth the effort to keep the withDefault* methods.

**Comment by texasbruce** [comment]
@danieldietrich Why don't we just return a wrapper class? Like how Scala does here: https://github.com/scala/scala/blob/706ef1b291134a5e5bce2275df2c222261f73451/src/library/scala/collection/immutable/Map.scala#L176 

This is little code change I think.

**Comment by danieldietrich** [comment]
@texasbruce

> This is little code change I think.

Don't underestimate the inherent complexity of collections. The worst part is the inheritance.

Creating a new collection type that introduces additional wrapper objects isn't a good trade for implicit default values. Also in the presence of a workaround.

I distinguish between two types of operations: _transformations_ (returning a new collection instance) and _terminal operations_ (returning values). The default values are only needed for a few terminal operations. Here we have a [workaround](https://github.com/vavr-io/vavr/pull/2590#issue-418957604).

Please also note that there exist transformations that change the domain, e.g.

```java
List(1, 2, 3)
   .withDefaultValue(-1)
   .flatMap(String::valueOf) // changes domain from int to String
   .get(10); // throws IndexOutOfBoundsException
```

I really question the value of this feature. I prefer to have explicit default value handling using existing methods like `getOrElse` or `getOption`. I consider _implicit_ default values to be unsafe.

**Comment by texasbruce** [comment]
Not sure that's a concern of LSP. Scala has this behavior in their standard library and it is working fine. Also not sure what the cost refers to, it is literally just a typical delegate.

**Comment by danieldietrich** [comment]
I really don‘t see a problem here. We don‘t loose something by removing the existing methods. There exists a workaround than is nearly the same:

![image](https://user-images.githubusercontent.com/743833/82156684-fc087200-987c-11ea-8b76-754aba1ed2fe.jpeg)

Regarding the delegating wrappers: I question their usefulness and want to leave them away for now. Scala isn‘t doing all things right.
