### ISSUE TITLE
Build instructions might need little more detail

### ISSUE THREAD

**Issue by sheldon-white** [javaslang/javaslang#1327]
I tried pulling the sources from git, updating my ~/.m2/settings.xml file (adding the <server> entries mentioned in the guidelines and the sonatype profile), then running maven. I got a lot of errors involving sonatype connectivity. If there's some extra setup required, this should be documented or at least called out, but since I just want to build and run locally there shouldn't be any need for special repository setup.

EDIT: I was able to get this working by removing the <parent></parent> section in the top pom.xml - but that's not necessarily ideal.

<code>
garnet:/Users/swhite/projects/javaslang> mvn clean test
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.javaslang:javaslang-parent:2.1.0-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to central (${repoBaseUrl}/libs-release): Cannot access ${repoBaseUrl}/libs-release with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 27, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.javaslang:javaslang-parent:2.1.0-SNAPSHOT (/Users/swhite/projects/javaslang/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.javaslang:javaslang-parent:2.1.0-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to central (${repoBaseUrl}/libs-release): Cannot access ${repoBaseUrl}/libs-release with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 27, column 13: Cannot access ${repoBaseUrl}/libs-release using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
garnet:/Users/swhite/projects/javaslang> 
</code>

**Comment by danieldietrich** [comment]
Hi Sheldon,

what is your use-case?

1. **Developing Javaslang** If you check out the sources from Github you do not need to modify your Maven settings. It should just work because Javaslang is on your local machine.
2. **Building a Javaslang snapshot from Sources on the local machine and referencing it from another local Maven Project** If you do a `mvn clean package` the Javaslang snapshot is installed to your local maven repository. Other local maven projects that reference the Javaslang snapshot will load it from the local maven repository then. Here is also no sonatype sepcific configuration needed.
3. **Having a Javaslang snapshot dependency without having Javaslang sources checked out** This is the use-case described in the Javaslang docs. The dependency has to be loaded from sonatype. The sonatype repository needs to be added either to the maven settings.xml _or_ to the pom of the local project.

If your use-case is **3.** then you should add the [sonatype snapshot repo](https://oss.sonatype.org/content/repositories/snapshots) to [your local pom _or_ settings.xml](https://maven.apache.org/guides/mini/guide-multiple-repositories.html).

Maybe I should simplify the [maven docs](http://www.javaslang.io/javaslang-docs/#_maven_2)...

**Comment by sheldon-white** [comment]
Thanks for your response. I've successfully pulled and built the library as expected on a different machine, so there must have been some environmental issue on the first attempt.

**Comment by danieldietrich** [comment]
Great to hear, thanks!
