### ISSUE TITLE
Further improve/harden benchmarks and reports

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1328]
@eduardmanas has some great suggestions, starting at this comment:

https://github.com/javaslang/javaslang/pull/1324#issuecomment-218821324

**Comment by eduardmanas** [comment]
I think the way to go is to remove outliers from the iteration runs. 

The idea is that some iteration runs will be impacted by the GC, and we should remove those iterations from the final statistics.

As a proof of concept, I have updated the current `BenchmarkResultAggregator` to exclude the 20% iterations with higher and lower throughput.  When calculating the ratios using `Warmup=5, Iterations=20`, I am getting ratios very similar to those I get using `Iterations=50` (i.e. ratio difference between runs is approx 2%)

[RatioCalculator.java.txt](https://github.com/javaslang/javaslang/files/262711/RatioCalculator.java.txt)

**Comment by eduardmanas** [comment]
Added pull request https://github.com/javaslang/javaslang/pull/1331

**Comment by eduardmanas** [comment]
Another pull request: https://github.com/javaslang/javaslang/pull/1335

**Comment by paplorinc** [comment]
It seems strange to me that we're removing the highest throughput, since that should've had the best SNR, i.e. the cleanest run.

FYI, using `-XX:+PrintGC` (or `-verbose:gc`) shows that there is some minor `GC` activity going on, often even after warmup.
For `ArrayBenchmark`, with no forced `GC` activity between measurements (`.shouldDoGC(false)`) and a `1g` heap, it has `72` youngs; with `4g` heap only `26`, .
Forcing `GC` between runs reduces it to `5`, happening only in the warmup period.

Increasing the young generation size to the entire allocated heap (`XX:G1NewSizePercent=100`) made the young generations disappear (for bigger sample size setting `XX:MaxGCPauseMillis` to a big value -- so that it happens infrequently -- reduced the needed intermediary youngs):

```java
    @Fork(value = 1, jvmArgsAppend = { "-server", "-XX:+UseG1GC", "-Xss100m", "-Xms4g", "-Xmx4g", "-XX:+PrintGC", "-XX:+TieredCompilation", "-XX:CompileThreshold=1500", "-XX:MaxGCPauseMillis=1000", "-XX:+UnlockExperimentalVMOptions", "-XX:G1NewSizePercent=100", "-XX:G1MaxNewSizePercent=100", "-disableassertions" }) /* set fork to 0 if you want to debug */
```

Will create a `PR` with these settings for the existing benchmarks.

**Comment by paplorinc** [comment]
I think this can be closed.
@danieldietrich, @eduardmanas?

**Comment by danieldietrich** [comment]
Yep, I also think it can be closed. Let's wait for Eduard's answer.

**Comment by eduardmanas** [comment]
Yep, please close!
