### ISSUE TITLE
Flatten for List

### ISSUE THREAD

**Issue by atrianac** [javaslang/javaslang#1329]
Could you implement the flatten method in List (as Scala does?)

**Comment by danieldietrich** [comment]
Yes, I planned that. However, because of the lack of type constructors/higher kinded types in Java, we cannot implement it as instance method, it has to be a static method that takes the instance.

I'm currently not sure how to implement flatten of interfaces like `Seq.flatten(Seq)`. Applied to a `List` it should return a `List` instance, for a `Queue` a `Queue` instance and so on. I don't want to implement a big switch with different cases. That does not scale well...

**Comment by danieldietrich** [comment]
Btw - a workaround is `that.flatten(Function.identity())`

**Comment by danieldietrich** [comment]
Duplicate to #241

**Comment by evantill** [comment]
> Btw - a workaround is `that.flatMap(Function.identity())`

Why not add a flatten() method that do exactly that ?

**Comment by danieldietrich** [comment]
@evantill unfortunately that is not possible in Java:

```java
class List<T> {
    // problem: we assume that List<T> is List<List<U>> but we can't infer U ...
    List<U> flatten() { ... }
}
```
