### ISSUE TITLE
Provide IntelliJ Idea settings xml for code styling

### ISSUE THREAD

**Issue by ggalmazor** [javaslang/javaslang#133]
I've noticed that files use a mix of tabs and spaces and that some one-line sentences are kept that way after automatic reformatting in Idea.

It would be helpful to define a main code style, export it (with File > Export Settings) and commit it into the repo for contributors.

Also, I'd suggest to use only spaces for indenting and to convert automatically tabs to spaces when formatting.

**Comment by danieldietrich** [comment]
I'm on it!

**Comment by danieldietrich** [comment]
The file `generator/Generator.scala` and the whole dir `src-gen` have to be excluded, currently manually or by reverting formatting changes.

I have to update some javadoc comments because the IntelliJ formatter is producing javadoc incompatible to doclint of java 8 which breaks the (travis-ci) build (when releasing).

@ggalmazor Any suggestions on which settings to export. I don't want to export all (my own color scheme etc.). I think `File templates` are a good idea to get the Javaslang file header. **Do you have an idea which export option is responsible for the `Editor > Code Style > Java` settings?**

**Comment by ggalmazor** [comment]
You could throw in Code Style, File templates and maybe toString templates (as you've defined it in the contribution guide).

Take into account that those settings are imported in a separate profile so it doesn't collide with previous settings that we could have :)

**Comment by ggalmazor** [comment]
Inspection Profiles! I forgot.

**Comment by danieldietrich** [comment]
Thx! - ohh, I overlooked the first option `Code Style`.

This is the current list of settings:

* Code Style
* File templates
* Inspection profiles

Will push the changes in a sec...

**Comment by ggalmazor** [comment]
Great!

**Comment by danieldietrich** [comment]
Waiting for travis-ci [build #666](https://travis-ci.org/javaslang/javaslang/builds/58055332) of the pull request. o_O
