### ISSUE TITLE
Add ForN.apply?

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang#1447]
i have a nested loop of side-effects... users, groups and i must apply all the groups to all the users. I would love to do that with `For` rather than nested loops but that's really side-effecting code.. `For` is lazy and takes value-returning functions. Could it make sense to add to `ForN` besides `yield` also something like `apply`? But the other issue with that is that javaslang doesn't have the required `ConsumerN` classes... I assume you already considered and rejected something like that?
that would look something like that:

    For(users, groups).apply((user, group) -> user.addGroup(group))

It's achievable today with `yield` then `Tuple::of` then `forEach` and `tupled` but it gets way more verbose...

_EDIT_ I can make a PR if you're interested.

**Comment by danieldietrich** [comment]
We once had Consumers but removed it. I need to think about it if we really invest more energy in direction of side-effecting API. Maybe we should 'fall-back' to standard Java API instead of adding additional side-effecting 'functional' API (which is an **oxymoron**).

* https://github.com/javaslang/javaslang/issues/139
* https://github.com/javaslang/javaslang/pull/140/files
* https://github.com/javaslang/javaslang/issues/756

Need to think about it...

**Comment by danieldietrich** [comment]
We will not add ConsumerN classes to Javaslang. From the strategic viewpoint it is no good idea. With primitive generics Functions will be automatically Consumers. Adding Consumers now to Javaslang will blow up the types.
