### ISSUE TITLE
Consider removing Array in next major release

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1528]
In the next major release we will uncluttet Javaslang. There is a time of growth and also a time of renaturization.

Thanks to @paplorinc we will have a great collection for random access operations. Array heavily depends on array copy operations. I question that it will perform better than Vector for other than read and update operations.

Scala does not have an immutable Array baked into their collection lib (see [this](http://stackoverflow.com/questions/4825702/why-no-immutable-arrays-in-scala-standard-library)). So I ask here, is there a reason we stick to this type? /cc @ruslansennov @paplorinc 

Note: Don't fear to remove s.th. Human beings are interested to collect things over time and there is a deep fear to loose s.th. I experienced this when talking to coworkers about deleting code or documents. I'm a friend of removing things. It makes us free and created space for s.th. new.

Please provide me with your thoughts.

Also I'm interested in ideas what else can be fused, changed or removed to create a better and simpler future Javaslang.

\- Daniel

**Comment by ruslansennov** [comment]
Javaslang's `Array` specialization is only fast access and iteration along its elements (not update as you say). It seems upcoming `Vector` is fast enough to remove `Array` away.

**Comment by paplorinc** [comment]
If you think simplicity is more important than freedom of choice, than we should indeed remove `Array`.
But let's be braver than that and let's define criteria for why we're keeping the rest of the data structures, and if we have similar alternatives, let's consider them.

As you know I have a few suggestions to investigate.Again, I'm not saying we should throw out anything, just investigate and let the numbers speak for themselves (I recommended a few in other places, I'm repeating them here as I think the situation is slightly different. If not, just ignore them):
* Do we need `Stack` and `Queue` abstractions, if we don't want to provide alternatives?
* Are we certain the `banker's queue` is the best `queue` implementation? We should measure it against e.g. `Vector` or other impls that don't have linear operations (i.e. the 'amortized' reverse)
* We're reimplementing all the operations for `String` in `CharSeq`. Could we abstract those so that `CharSeq` is indeed just a `rich String`, without all that logic? Maybe add a primitivized `Vector<Character>` as an immutable `StringBuilder`, where most of the logic is already available?
* Could we use `Vector` in `BitSet` also, to make update non-linear there too?
* Are `Iterator` and `Stream` really that different? Couldn't we unify them somehow?

@danieldietrich, @ruslansennov, @zsolt-donca?

**Comment by paplorinc** [comment]
How will this affect the `toJavaArray` and `toArray` methods from `Value`?
Should we rename the former to the latter after the removal, to comply with `java.util.Collections`?

**Comment by danieldietrich** [comment]
Mmhh - let's first look at the final Benchmarks and compare Array and Vector. From what I can see `get()` will perform better for Array. If that is the case then Array should stay with us. Array could be helpful for fast reads.

**Comment by danieldietrich** [comment]
Let's keep it because of fast random read access.

**Comment by paplorinc** [comment]
Hmm, I though this was opened for gathering information in order to reach consenus.
You said we should wait for the final benchmarks, I still suggest we do that, or:

* `Vector` access is `~4x` slower, but is a **lot** faster in everything else. Is it worth the extra class?
* If people want a basically `immutable`, fast acces data structure, they can use any collection as a builder and call `.toJavaArray()` at the end.

I also recommended a few wild ideas [above](https://github.com/javaslang/javaslang/issues/1528#issuecomment-242202071).
I know most are out of reach, but it might be worth talking about them.
