### ISSUE TITLE
Include performance characteristics in Javadoc

### ISSUE THREAD

**Issue by udalrich** [javaslang/javaslang#1666]
It would be good if the Javadoc documented the expected performance characteristics of the methods.  For example, `List.size()` is hopefully `O(1)`, but as it is implemented as a linked list, it is plausible that it is `O(N)`.  

Similarly, I think the `List.append` is `O(N)`, while `List.prepend` is `O(1)`.  If that is correct and clearly documented, then it will be easier to avoid using the slower methods when they are not needed.

**Comment by danieldietrich** [comment]
Thank you for your suggestion.

The length/size of a collection is generally stored (for non-lazy collections that are traversable again). A size() call is considerably O(1).

The javadoc already contains an overview of general performance characteristics (see bottom of this page: http://static.javadoc.io/io.javaslang/javaslang/2.0.4/javaslang/collection/package-summary.html).

Adding the performance characteristics to each method's javadoc is fragile because it cannot be checked formally for validity. I like the overview, maybe we can add more information there?

**Comment by udalrich** [comment]
Thanks for the pointer.  I had not seen it before.  (I think I'm used to package summary pages not having any useful information.)

**Comment by danieldietrich** [comment]
Yes, maybe it is 'too hidden'. We may provide links at the collection javadoc and also add a section to the online documentation.

**Comment by danieldietrich** [comment]
Added performance characteristics section to online documentation: http://www.javaslang.io/javaslang-docs/#_performance_characteristics
