### ISSUE TITLE
Consider making CharSeq non-final, to allow Haskell-like type synonyms

### ISSUE THREAD

**Issue by the-james-burton** [javaslang/javaslang#1764]
It occurred to me that there is an opportunity with `CharSeq` to get close to a Haskell-like type synonym. If `CharSeq` was non-final it could be extended with an empty class to avoid writing the heavy boilerplate code associated with [tiny types](https://darrenhobbs.com/2007/04/11/tiny-types/).

I personally find myself often wishing I could do this in Java with `String` to gain additional type safety. I personally don't find the [arguments against](http://stackoverflow.com/questions/2068804/why-is-string-class-declared-final-in-java) a non-final `String` class very convincing. Given the source code, a determined coder can always find a way around immutability, so I think improved FP-like functionality is more desirable.

I am basically in support of [extensible strings](https://nofluffjuststuff.com/blog/joe_walker/2007/04/java_7_idea_extensible_strings) for `CharSeq` and I am curious if javaslang is sympathetic to this idea. 

What do you think? Is there a good reason why `CharSeq` is final and why you might not be prepared to make it non-final to allow for type synonyms?

I've also asked this question on stackoverflow [here](https://stackoverflow.com/questions/41187662/why-is-javaslang-charseq-final).

**Comment by danieldietrich** [comment]
Hi James,

I understand your desire, years ago I was also fascinated by the idea of extending existing final types in order to add functionality. The Java compatible language [Xtend](http://www.eclipse.org/xtend/) helps here by offering extension methods, which allow to seamlessly add new functionality to final types. With Scala's implicits we [can do similar things](https://github.com/javaslang/javaslang/blob/master/javaslang/generator/Generator.scala#L3541-L3569).

However, adding functionality using inheritance introduces several problems. The ones that come to my mind are:

* Inheritance breaks the symmetry property of equals. See [this explanation](http://stackoverflow.com/questions/12239344/why-should-i-not-use-equals-with-inheritance) on Stackoverflow.
* The second point is an implication of the first I think: We might get problems with pattern matching, which internally also relies on object identity (read: equals). For example Scala does also not allow to extend case classes, which are the basis for pattern matching in Scala. And I bet the upcoming values types (Project Valhalla/Brian Goetz) will also have to be final for similar reasons.
* Especially extending the implementations of [sum-types](https://en.wikipedia.org/wiki/Tagged_union) does not seem to make sense (example: Option = None or Some). Java does not have [higher-kinder types](https://en.wikipedia.org/wiki/Kind_(type_theory)) (aka type constructors). We are not able to overwrite methods like flatMap() in an appropriate way. I don't know if this is really an issue but we might break the monad laws.
* Several Javaslang classes adjust return types throughout the type hierarchy. E.g. in Traversable we have `Iterator<? extends Traversable<T>> sliding(int size);`. CharSeq has `Iterator<CharSeq> sliding(int size)` which cannot be overwritten with a more special return type anymore. (We would need to declare `Iterator<? extends CharSeq>`. I don't know if this is desirable from the API perspective. I decided not to do it for final types.

**There may be more points. But I think the equals() argument is a show-stopper.**

---

Personally I create static helper methods if I need additional functionality, like this:

```java
public final class StringExtensions {
    private StringExtensions() {}

    public static String firstUpper(String s) {
        return s.isEmpty() ? s : s.substring(0, 1).toUpperCase() + s.substring(1);
    }
}
```

Other languages have syntactic sugar, we have to call the helper method directly:

```java
// Scala and Xtend (maybe also Kotlin, C# and others)
"hello".firstUpper

// Java (using static import)
firstUpper("hello")
```

But I also understand that you want to add state-information to types, e.g.

```java
class UnicodeCharSeq extends CharSeq implements HasUnicodeCharacters {
    ...
}
```

Maybe you will find a workaround using [simulated union types](https://blog.jooq.org/2016/02/16/an-ingenious-workaround-to-emulate-sum-types-in-java/)!?

**Let's close this issue. I don't think it is a good idea to extend algebraic data types and value types in general.**

\- Daniel

**Comment by the-james-burton** [comment]
Hi Daniel, thanks for the comprehensive reply, it is very helpful! As I expected, you are thinking two or three steps ahead of me :) I don't really want or need to add functionality to my 'types'. I just want type safety so I can't get a `CustomerName` mixed up with a `CustomerAddress` in a constructor (or elsewhere) in code. 

In my mind, the object-oriented 'is-a' relationship is absolutely pure here... A `CustomerName` is a `CharSeq`. So using java extends seems correct and natural. Having a tiny type which obfuscates this into a wrapped 'has-a' relationship feels wrong to me.

Regarding the problem of equals, why not just declare it final in `CharSeq`? Would that address the concerns? In fact, every method could be made final in `CharSeq` and I would be happy, since I have no requirements for extension (especially if achieving that would compromise the design). This would possibly address your concerns 1 and 2.

Regarding concerns 3 and 4, I think they are deeper. I don't think issue 3 is relevant here as I am only talking specifically about the `CharSeq` class. Issue 4 is perhaps more of a concern. Maybe it would be safe to accept `<? extends CharSeq>` if all methods in `CharSeq` are final? 

Anyway, thanks again for taking the time to read and reply. I fully understand if you want to keep `CharSeq` final, but I thought it was worth asking. There is no way `String` is going to become non-final, that's for sure!
