### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by xenoterracide** [javaslang/javaslang#1772]
I don't understand this

> 
> This is how the new Java 8 Stream API works. It is a computational layer above the well known Java collections.
> 
> // = ["1", "2", "3"] in Java 8
> Arrays.asList(1, 2, 3)
>       .stream()
>       .map(Object::toString)
>       .collect(Collectors.toList())
> Javaslang is greatly inspired by Scala. This is how the above example should have been in Java 8.
> 
> // = Stream("1", "2", "3") in Javaslang
> Stream.of(1, 2, 3).map(Object::toString)
> 

Both are valid java 8, you don't have to start with a list or collect to a list, are you just saying it's a bad example of how to do things? I of course do think it's relevant to show how to collect to a collection, or join to a string, etc.

**Comment by danieldietrich** [comment]
@xenoterracide thank you for your question.

j.u.s.Stream is a completely different concept to existing collection libraries like those of Scala, Clojure ... and Javaslang. Java's Stream is just an Iterator. Given that you can't access specific elements or reuse it (e.g. by one or more threads). 

My point is that Java 8 introduces lambdas but does not offer a new collection API (from the user perspective). It adds the new Stream API whose main purpose is to make it easier to perform parallel computations using the fork-join framework introduced in Java 7.

When it comes to sequential computations, javaslang.collection.Iterator is better alternative to j.u.s.Stream which much more mature API and the same(!) performance characteristics (modulo primitive types - but this will be solved with Project Valhalla/primitive generics).

In [Section 6 of Oracle's Secure Coding Guidelines for Java SE](http://www.oracle.com/technetwork/java/seccodeguide-139067.html#6) it is highly recommended to pass around immutable data objects. More specifically you will neither pass around j.u.s.Stream, nor you will pass around a mutable Java Collection - for a good reason.

So, from the user perspective we need to stream/process/collect data. That is cumbersome. Other languages/libraries show, how to do it better.

---

As I saw the new Java 8 API I thought "No, not really!?!?" Why we should complicate things by another layer of indirection - and type more code...

**Standard Java**

```
COMPUTATIONAL LAYER
     x-----------x
_ _ _^_ _ _ _ _ _|_ _ _ _ _
     |           v
>----x           x----->
DATA LAYER
```

... instead of doing it the direct way???

**Javaslang**

```
>----x-----------x----->
DATA LAYER + COMPUTATION
```

**Comment by danieldietrich** [comment]
I think the documentation is correctly pointing to the nature of Java's Stream being an Iterator:

```java
// i + 1
i.prepareForAddition()
 .add(1)
 .mapBackToInteger(Mappers.toInteger())
```

In this context the documentation also mentions the [BDSBTB 2015 keynote](https://www.youtube.com/watch?v=NW5h8d_ZyOs) of Martin Odersky. He was the first who declares Java's Stream as "fancy form of an Iterator".

I think there is nothing wrong with the documentation. Otherwise please suggest how to improve it.
