### ISSUE TITLE
Add factory method to Try for Supplier interface

### ISSUE THREAD

**Issue by RobWin** [javaslang/javaslang#1811]
* [x] Try
* [x] Future

---

Hi,

I often use the Supplier interface so that I can decorate a method call and then I want to invoke the Supplier interface. It would be nice if `Try` would have a factory method for the Supplier interface. For example:

```
   Supplier<String> supplier = () -> businessService.doSomething("input");
   Supplier<String> decoratedSupplier = CircuitBreaker.decorateSupplier(circuitBreaker, supplier)
   Try.of(decoratedSupplier).get();
```

Instead of

```
   Try.of(decoratedSupplier::get).get()
```

The same also applies to the `Callable` interface.

What do you think?

**Comment by danieldietrich** [comment]
I'm afraid, this is not possible - at least when using the same method name `of`, because it will raise ambiguities.

From the viewpoint of the compiler

* a lambda `() -> retVal` matches both signatures `Supplier`, `CheckedSupplier` and `Callable`
* a lambda `() -> {}` matches the signatures `Runnable`, `CheckedRunnable`

So only one is possible when having the same method name `of`.

I think it is not worth to introduce additional API, e.g.

* `Try.ofCallable(Callable)`
* `Try.ofSupplier(Supplier)`
* ...

Just calling

* `Try.of(supplier::get)`

should be sufficient.

---

If you agree we should close the ticket.

**Comment by RobWin** [comment]
Damn, that's true. Haven't thought of that, if you use a lamba directly instead of an interface.
You have to decide it. Other libraries like RxJava provide factory methods for this use case, for example:

`Observable. fromCallable()`

**Comment by danieldietrich** [comment]
I thought a moment about removing Try.CheckedSupplier (in 3.0.0) and using Callable instead. But a CheckedSupplier throws Throwable and Callable throws Exception. It does not completely fit our needs.

We use the static methods `fromXxx()` to convert a value _from_ one to another. It is the dual operation to `toXxx()`. Example:

* Validation.fromEither()
* Validation.toEither()

To to disambiguate `of(CheckedSupplier)` and `of(Callable)`, the right name would be `Try.ofCallable(Callable)` (`fromCallable` does not fit because no conversion takes place).

To to disambiguate `of(CheckedRunnable)` and `run(Runnable)`, the right name would be `Try.runRunnable(Runnable)` (which looks a bit weird).

To be congruent with Future, we need there also `Future.ofCallable(Callable)`, `Future.ofCallable(ExecutorService, Callable)`, `Future.runRunnable(Runnable)`, `Future.runRunnable(ExecutorService, Runnable)`

If it helps I'm fine with adding the methods.

**Comment by RobWin** [comment]
Yes, I also thought about replacing CheckedSupplier with Callable, but came to the same conclusion that Javaslang still needs `Try.CheckedSupplier` (or use `CheckedFunction0` instead?).

What about?

```
Try.ofCallable(Callable callable)
Try.ofSupplier(Supplier supplier)
Try.runRunnable(Runnable runnable)

Future.ofCallable(Callable callable)
Future.ofSupplier(Supplier supplier)
Future.runRunnable(Runnable runnable)
```

**Comment by danieldietrich** [comment]
> (or use CheckedFunction0 instead?)

The Try.Checked* functions are a workaround. With Project Valhalla (primitive generics) we will remove the Try.Checked* methods and have

* CheckedFunction0&lt;R> extends CheckedFunction1&lt;void, R>
* CheckedFunction0&lt;void> instead of Try.CheckedRunnable
* CheckedFunction0&lt;R> instead of Try.CheckedSupplier&lt;R>
* CheckedFunction1&lt;T, boolean> instead of Try.CheckedPredicate&lt;T>
* ...

For now we leave it as is.

> What about?

Looks good. Additionally we need the ExecutorService param for Future:

```java
Try.ofCallable(Callable callable)
Try.ofSupplier(Supplier supplier)
Try.runRunnable(Runnable runnable)

Future.ofCallable(Callable callable)
Future.ofSupplier(Supplier supplier)
Future.runRunnable(Runnable runnable)

Future.ofCallable(ExecutorService executorService, Callable callable)
Future.ofSupplier(ExecutorService executorService, Supplier supplier)
Future.runRunnable(ExecutorService executorService, Runnable runnable)
```

**Comment by RobWin** [comment]
Shall I create a PR for Try?

**Comment by danieldietrich** [comment]
Yes, would be cool!

**Comment by RobWin** [comment]
Done
