### ISSUE TITLE
Why pattern matching does not unwrap the nested monad.

### ISSUE THREAD

**Issue by noorulhaq** [javaslang/javaslang#1824]
In below code snippet I have to call **get** operation on **str** to get the actual value. Although, I am in the right case statement.  

```java       
 Try<Option<String>> tryOpt = Try.of(()->Option.of("Test"));

        String string =  Match(tryOpt).of(
                Case(Success(Some($())), (str) -> str.get()),
                Case(Success(None()), (str) -> null)
        );
        System.out.println(string);
```

**Comment by noorulhaq** [comment]
Also for ***Case(Success(Some($()))*** I cannot return ***Try.failure()***. Which I need for some business exception. Same can be done in scala.

**Comment by danieldietrich** [comment]
Thank you for your question. I know, it is a little bit confusing. There are two rules regarding pattern matching:

1. A whole dependency tree can be matched (as in your case)
2. Only *the first layer* will be decomposed due to limitations of Java

You ran into the 2. rule and expected that all $() occurrences will be extracted, regardless of the depth of occurrence within the object tree.

In fact it _somehow_ worked in my first prototype of pattern matching. But all possible combinations of handlers / patterns had to be generated by the pattern compiler. The complexity exploded and often it exceeded the maximum size of bytecode of a class. Also the compiler seemed to need infinite time to compile these expressions or user-defined match cases. It wasn't practicable.

If there is a single value, the Case handles that value, like `Case($(1), one -> ...)`.

If there is a composed value, the Case handles the first layer of the object tree:

```java
Case(Some(List(None(), Some($()), Some(Tuple2(Left($())), ... )), list -> ...)
```

---

I know that it would be better to have it like Scala but that was the best we could come up with regarding the limitations of Java's type system.

Hopefully this helps a bit.

\- Daniel

**Comment by noorulhaq** [comment]
Thanks for the explanation. I had the same hunch that this might cause performance problems. Anyways, thanks for the explanation. I can manage with some extra gets until I am confident that I am doing in right context.

**Comment by danieldietrich** [comment]
Thank you.
