### ISSUE TITLE
Wish: Greater Arity of functions and tuples

### ISSUE THREAD

**Issue by hamnis** [javaslang/javaslang#1839]
I have written a typesafe Json library, found at https://github.com/hamnis/immutable-json which
heavily uses Tuples and functions for Encoding and Decoding json and types.

Scala has Tuple 22 and Function 22, which is enough for most users, If not you need a HList or something like that ( which is possible to encode in Java, but not really practical )

**Comment by paplorinc** [comment]
Since all these are generated, I pushed a PR containing a partial fix: https://github.com/javaslang/javaslang/pull/1848

**Comment by paplorinc** [comment]
@hamnis, could you please take a look at the PR?

**Comment by hamnis** [comment]
@paplorinc as partial fix, that is fine. I would still really want more =)

**Comment by paplorinc** [comment]
@danieldietrich decided :)

**Comment by danieldietrich** [comment]
@hamnis what is the specific use-case for greater arity in your JSON lib? JSON itself has no notion for tuples or do you encode lists as tuples and fall back to HList at some point?

**Comment by hamnis** [comment]
@danieldietrich encoding and decoding into user defined types.

https://github.com/hamnis/immutable-json/blob/master/codec/src/main/java/net/hamnaberg/json/codec/Codecs.java#L326

https://github.com/hamnis/immutable-json/blob/master/codec/src/main/java/net/hamnaberg/json/extract/Extractors.java#L88

use:
https://github.com/hamnis/immutable-json/blob/master/codec/src/test/java/net/hamnaberg/json/extract/ExtractorsTest.java#L40-L47

**Comment by danieldietrich** [comment]
@hamnis Thank you for the links. I see, Tuples are needed in Codecs (especially in Iso). However, currently the extraction of JSON objects is bound by the max Tuple arity. If there is Tuple22, you can extract only 22 fields. A better scalable solution would be unbounded, i.e. would allow to extract JSON objects of arbitrary size.

I've sketched a HList impl here: https://github.com/javaslang/javaslang/issues/237#issuecomment-171659133

Maybe you could use HList instead of Tuple*?

---

I will close this issue for now. May Javaslang does also need an HList for greater Tuple arity. I would be really interested if you get practical experience with HList!

**Comment by danieldietrich** [comment]
@hamnis Bad news - our javaslang-gwt module does not return from build anymore since we bumped arity from 8 to 10. Maybe the GWT compiler is unable to cope with the generics anymore. We need to revert back to arity 8 until the GWT issue is solved, sorry :-/

Maybe one more reason to test an HList implementation.

**Comment by ruslansennov** [comment]
We should wait for any news from @paplorinc 
He promised to check out gwt building

**Comment by paplorinc** [comment]
yup, doing it as we speak :)

**Comment by danieldietrich** [comment]
I will hold my horses!
