### ISSUE TITLE
Return Option from javaslang.collection.Traversable#mkString(...) 

### ISSUE THREAD

**Issue by mind-blowing** [javaslang/javaslang#1840]
It will be nice to have additional alternative methods of `javaslang.collection.Traversable#mkString(...)` which will return `javaslang.control.Option`, it may be useful in case if after all manipulations we got empty string and we want to return default value in this case.

For example, with new method `mkOptionString(...)` it may looks like this:
```
CharSeq.of("000000000")
       .dropWhile(is('0'))
       .mkOptionString()
       .getOrElse("0");
```

Currently it is possible by doing something like this:
```
Option.of(CharSeq.of("000000000")
                 .dropWhile(is('0'))
                 .mkString())
      .filter(noneOf(String::isEmpty))
      .getOrElse("0");
```

**Comment by paplorinc** [comment]
I think this could be generalized via a default-if-empty method (maybe in `Traversable`):
```java
public CharSeq defaultIfEmpty(CharSeq defaultValue) {
    return isEmpty() ? defaultValue : this;
}
public CharSeq defaultIfEmpty(Supplier<CharSeq> defaultValue) {
    return isEmpty() ? defaultValue.get() : this;
}
```
giving the following solution to your problem (with `API.CharSeq` static import):
```java
CharSeq("000000000")
       .dropWhile(is('0'))
       .defaultIfEmpty(CharSeq("0"))
       .mkString();
```
-> `0`

```java
CharSeq("000000000")
       .defaultIfEmpty(CharSeq("0"))
       .mkString();
```
-> `000000000`

What do you think, @danieldietrich?

**Comment by danieldietrich** [comment]
@paplorinc I like you suggestion of having a method that defaults to a specific object in the empty case. We know it already from Scala, it's name is `orElse`.

The problem with `orElse` is, that we need higher-order types in order to define it properly throughout the type hierarchy. For that reason Value does not declare that method. Instead All subtypes of Value (but Traversable) define it. (See also #909)

Currently Traversable does not define it because the problem still remains - we can't define a proper method signature that works well throughout the Traversable hierarchy:

```java
interface Traversable<T> extends Value<T> {
    Traversable<T> orElse(Traversable<? extends T> other);
}

interface Seq<T> extends Traversable<T> {
    @Override   // v---- does not compile
    Seq<T> orElse(Seq<? extends T> other);
}
```

We could create alternate method signatures that 'behave as expected':

```java
interface Traversable<T> extends Value<T> {

    Traversable<T> orElse(Iterable<? extends T> other);

    Traversable<T> orElse(Supplier<? extends Iterable<? extends T>> supplier);
}

interface Seq<T> extends Traversable<T> {

    @Override
    Seq<T> orElse(Iterable<? extends T> other);

    @Override
    Seq<T> orElse(Supplier<? extends Iterable<? extends T>> supplier);
}
```

The implementations look like this:

```java
isEmpty() ? ofAll(other) : this;
```

**Comment by danieldietrich** [comment]
Fixed by @ruslansennov
