### ISSUE TITLE
Lazy.filter() is not lazy

### ISSUE THREAD

**Issue by pivovarit** [javaslang/javaslang#1861]
@Test
    public void e00() throws Exception {
        Lazy.of(() -> {
            System.out.println("Calculating...");
            return "42";
        })
          .map(String::toUpperCase)
          .filter(s -> s.length() > 5);
    }

Output:
`Calculating...`

Affected versions: 2.1.0-alpha

**Comment by danieldietrich** [comment]
@pivovarit Lazy.filter() can't be lazy, it returns an Option, not a Lazy:

```java
public Option<T> filter(Predicate<? super T> predicate) {
    ...
}
```

We designed a Lazy value in the way that it holds a value that is evaluated only, when accessed. Lazy is not meant to be empty, i.e. it can't be a `lazy non-value`:

```java
@Override
public boolean isEmpty() {
    return false;
}
```

However, we have `getOption()` in order to make `get()` safe.

We could change the behavior of Lazy (by adding the empty state and making filter lazy) but it will be a breaking/bytecode incompatible change. We need to defer it to 3.0.0.

**Comment by pivovarit** [comment]
@danieldietrich ok, thanks for the clarification :)

**Comment by danieldietrich** [comment]
@pivovarit making filter() lazy looks more consistent to my eyes, so let's do the change in 3.0.0

**Comment by danieldietrich** [comment]
See #1122

**Comment by danieldietrich** [comment]
**Note to myself:**

> making filter() lazy looks more consistent to my eyes

This would be a [foolish consistency](http://www.goodreads.com/quotes/353571-a-foolish-consistency-is-the-hobgoblin-of-little-minds-adored)

### `lookMaIGotALazyValue.get()`

![lazy-evaluation](https://cloud.githubusercontent.com/assets/743833/23630197/6ae37758-02ba-11e7-91c7-30300c584205.gif)

_(the get() call above could throw if we allow a Lazy to be empty)_

Evaluating a lazy value should not produce any unforeseeable surprises.

**Comment by danieldietrich** [comment]
However, it might be important that filter() returns a Lazy in the case of filtering For comprehensions. (See Scala's FilterMonad)
