### ISSUE TITLE
'infinite' Stream explodes with OOM

### ISSUE THREAD

**Issue by densmnko** [javaslang/javaslang#1881]
According to javadocs: "An immutable Stream is lazy sequence of elements which may be infinitely long". But in real life its infinite only with infinite memory amount. 

Running simple test (with -Xmx8m) throws OOM: 
`assertTrue(1L == Stream.continually(1L).drop(100_000_000L).head());`

Imho, i don't explicitly retain the head in this eхample.
Do we really have infinite streams in javaslang?

**Comment by danieldietrich** [comment]
This is a valid question. The Stream class is designed to represent infinite sequences. If the example throws, it is a bug.

I ran the example in Scala. It successfully finished with the expected result:

```bash
scala> Stream.continually(1).drop(100000000).head
res0: Int = 1
```

---

I expect we have a memory leak. More specifically I think that a lambda captures the outer scope, namely `this` Stream. As a result, dropping elements does not release memory. The head elements are still wired to the tail.

We need to further investigate it...

**Comment by danieldietrich** [comment]
@densmnko On the current master (2.1.0-SNAPSHOT) it works fine on my machine. Even faster than Scala! Which version of Javaslang do you use?

| Number of Elements | Time (Javaslang) | Time (Scala) |
| --- | --- | --- |
| 100_000_000 | 4 sec | 5 sec to 15 sec |
| 1_000_000_000 | 37 sec | 50 sec to 158 sec |

I don't know why different Scala runs vary that much. Javaslang runs are time-stable.

Please note that I did not adjust the memory configuration of Java. It was IntelliJ's resp. Scala REPL's default value.

Please also note, that I used ints instead of longs:

```java
Stream.continually(1).drop(1_000_000_000).head();
```

---

**My system config:**

MacBook Pro
2,9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Scala code runner version 2.12.1

**Comment by danieldietrich** [comment]
Jeppe Cramon gave me [a hint]() that your low heap might has been caused the OOM exception (I first thought the heap was 8g to give more space to compute).

I re-ran your original the Javaslang example (with 100_000_000 elements) on my machine using 2.1.0-SNAPSHOT and the VM option -Xmx8m. Again, all worked fine (the GC had clearly more to do):

For 100_000_000 elements it now took from 5 sec. to 20 sec.

**Comment by densmnko** [comment]
@danieldietrich Thanks a lot for your investigation. It seems that a problem was not in javaslang at all. After disabling "Fluid" IDEA plugin all my tests passed without any leaks... 
Sorry for bothering, and thanks a lot.

**Comment by danieldietrich** [comment]
@densmnko Thanks, good to know! It was fun to test it anyway 😊
