### ISSUE TITLE
change the method Name Tuple.of() to Tuple.tupelOf().

### ISSUE THREAD

**Issue by aranikrishna** [javaslang/javaslang#1942]
I propose the method name to be changed from Tuple.of to Tuple.tupleOf() so that even if we use static imports code is more readable and having method name clearer is always good.

**Comment by danieldietrich** [comment]
Hi @aranikrishna,

thank you for your suggestion.

I've thought about the same when designing the Javaslang API. I searched for a way to add _Scala features_ in a _Java way_.

In Java 8 we have Optional.of() and Stream.of(). Java 9 will introduce [collection factory methods](http://iteratrlearning.com/java9/2016/11/09/java9-collection-factory-methods.html) List.of(), Set.of() and Map.of(). Having of() factory methods seems to be streamlined. So you will find of() factory methods in almost all Javaslang types.

Another argument for having of() methods is the steep learning curve. I want a Future - I type Future.of(...). I want a Tuple, I type Tuple.of(...). I want a Map, I type Map.of(...). Easy.

Generally, I aligned Javaslang to Scala. In Scala a class may have a companion object. That object has static factory methods, one of them is apply(). Instead of MyType.apply(...) we may write the _sugared_ form MyType(...).

In Java we do not have that kind of syntactic sugar. In order to simplify things I added API.* to Javaslang, which will be released with 2.1.0. The idea is to add one import to access most of the Javaslang API:

```java
import static javaslang.API.*;

// instead of Tuple.of(x, y, z)
Tuple(x, y, z)

// instead of Set.of(1, 2, 3)
Set(1, 2, 3)

// instead of Option.of(x)
Option(x)

// instead of Option.some(1)
Some(1)
```

As you see, we already have thoroughly designed the API. Changing it would mean to break it. Currently I see no reason to do that.

I will close this issue and hope I could clarify the design decision a bit.

Thank you,

\- Daniel
