### ISSUE TITLE
How to resolve name clashes of collections?

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#232]
In particular, `List` and `Stream` have name conflicts with their `java.util` and `java.util.stream` counterparts. An attempt to prefix a 'J' resulted in a name conflict with `javax.swing.{JList}`.

How to name things is relatively opinionated. From the technical perspective name clashes are distracting.

How about prefixing an underscore '_', i.e. `_List` and `_Stream`? I like that. They are no `AList`, `BList`, ..., `ZList` etc. This looks ugly. Also lower case chars `aList`, `bList`, ..., `zList` are not Java conform. '$' has another meaning and is internally used in conjunction with inner classes.

Personally I use underscore to solve naming conflicts. I.e. my Reddit name is '_danieldietrich' and the Twitter account of this projects is named '_Javaslang' because of name clashes. Underscore does not get in the way while reading, it has no meaning, like other characters.

Also consistency is a point. There are many collection types without name clashes, i.e. `Tree`, `BinaryTree`, `RoseTree`, `Seq`, ... Do we need to prefix them also to be consistent?

Note: There are also upcoming `_Set` and `_Map`.

**Comment by martin-g** [comment]
I personally don't mind the clashes. I like Scala's import renaming but I don't mind using FQN in Java when needed.
Here is another solution: add `_Name` as an alias of `Name`, e.g.:
```java
package javaslang.list;
public class List {
...
}
```
```java
package javaslang.list;
public class _List extends javaslang.List {}
```
This way people can import the _Name if they prefer it.

**Comment by danieldietrich** [comment]
**Great idea!** Have to think about providing aliases. Most collections are interfaces with static factory methods to get concrete instances. Static interface methods are not inherited.

I agree, FQN are arguable. Javaslang collections play well together with the Iterable interface, this can also be used instead of the specific class names.

Here is a (currently broken) example of bundling aliases per package. Here an experimental `alias` interface is used, starting with a lower case. This could be seen as a kind of _module_ which is both, a _class_ and a _package_.

```java
package javaslang.collection;

interface alias {
    interface _List<T> extends List<T> {
        // duplicate all static List methods here
        static <T> _List of(T... elements) {
            // BROKEN: Need a _List instead of a List
            return List.of(elements);
        }
    }
    interface _Stream<T> extends Stream<T> {
        // duplicate all static Stream methods here
    }
}
```

Usage:

```
import javaslang.collection.alias.*;

// ...

_List.of(1, 2, 3);
```

**Comment by danieldietrich** [comment]
...thinking of an alias generator which follows the scheme mentioned above. Alias modules containg `_Original` interfaces can be theoretically generated automatically using reflection with overridden methods `_Original method(args)` where necessary (modulo generics?). `Proxy` will do the rest?

**Comment by nedtwigg** [comment]
I am the reddit commentor who objected to the name clashes.  Big fan of the library, looking forward to trying it!  I have lots of List and Stream in my code, and I didn't like that there would be ambiguity about which List and Stream.

As I was looking at this, I just realized that the gui toolkit that I use (SWT) has a "List" class, but it's used so differently from a java.lang.List that I don't ever recall any confusion.  On the other hand, that toolkit also has a "Color" class, and I frequently have 10 seconds of confusion as I realize my IDE grabbed the Swing/AWT Color instead of the SWT Color, because they are harder to distinguish in context.

In your case, your Stream and List will be used similarly to the java.lang versions, so it seems like a name change might be worthwhile. I would have guessed that the prefix for your library would be "S" for Slang, or possibly "F" for functional, but I see "J" as defacto the JDK's prefix.

Having aliases seems to violate the "simplest possible solution".  IMO, library version numbers are arbitrary, and there's nothing wrong with bumping a major version to indicate a name change.  A lot of libraries seem to spend a lot of time in 0.x, and don't want to go to 1.x or 2.x unless there's some major redesign.  I think library version numbers are most valuable if they are used exclusively and ruthlessly as semantic indicators.

I recently encountered almost the same problem in an open source library that I maintain, [here was my reasoning, FWIW](https://github.com/diffplug/durian/commit/5f9bf016edede7a6927fa39b28b667d7050628c6). (aside: the class referenced in this commit is in serious risk of being deprecated for your excellent Try class :)

**Comment by danieldietrich** [comment]
Hey! Of course you're right - we search the simplest solution possible, there will be no aliases using reflection voodoo magic proxy mechanisms lingering around in Javaslang :-)

The control package is fixed, so are the collections. The only experimental feature is the match API. With #227 it will be also fixed in the next release, too. I should have been started with a 0.x version but now we are at 1.x and can't move back. I think this is ok. The monadic types and collections are already battle-hardened. I do not expect much API movement.

Back to your question, I'm still not convinced prefixing the collections. Mostly because the Java collections are outdated IMO. New code should not rely on them any more. Javaslang's collections are replacements and not considered as alternatives. I'm aware of the fact that java util collections will be among us for many years, maybe the rest of our lives, but my vision is to go to the next level. I think this is the Slang part of Javaslang :-)

**Comment by nedtwigg** [comment]
There are 3 groups you can optimize your library for:

A) People who are already using Javaslang
B) People who are starting a brand new project, and want to jettison java.lang.List, and any library that uses java.lang.List

For these people, it is better if you don't change the names.

C) People who are developing and improving an existing project, or starting a brand new project that will need libraries that use java.lang.List

For these people, it is easier to adopt your project if you do change names.

You are in groups A and B, and probably so are most of the people you talk to about your project.  But of all the programmers out there who might use your project, the vast majority are in group C.

[Guava has ~1,000 libraries in MavenCentral that depend on it](http://mvnrepository.com/artifact/com.google.guava/guava), and has java.lang.List all over its API.
[Javaslang has 0 libraries in MavenCentral that depend on it](http://mvnrepository.com/artifact/com.javaslang/javaslang), which means you can still change API without breaking things for 1000's of people.

I would consider my company to be an "early-ish adopter" of functional programming, but we've gotta keep shipping a new version to our real-life users every couple weeks, and they don't care about functional programming (or even programming at all, really).  There's no way I could budget a "stop the world" and replace all of our List.  And even if I did, I definitely couldn't rewrite all of our dependencies so that they don't use java.lang.List either (including transitive dependencies, we have literally 100's).

When Java 8 came out, we were able to incrementally add lambdas and a functional-style to our code, updating as we went, and it never caused any confusion.  Giant projects like Eclipse are starting to undertake the same effort.  If we wanted to adopt the advantages of Javaslang, it would be quite confusing when our project gradually reached the state that half of our "List" weren't actually "java.lang.List", especially for a new team member.

I think it's great that you're rejecting the problems with List and Stream, and creating the kernel of a newer, cleaner java.  But I think you'll have more users if you optimize for gradual adoption, rather than optimizing for clean-slates.

But of course, it is your project, and a great one at that, so I look forward to using it in some capacity regardless of your decision :)

**Comment by danieldietrich** [comment]
Yes, I know what you are talking about :-) At $work we have a legacy Java system with gigabytes of transitive dependencies. Our vendor started development in the 90s. A big amount of classes is still not typed with generics - it's a nightmare. 

Here is a List of possibilities to name things:

```java
// import javaslang.collection.List;
List<T> compute(List<T> input) {
    // this is the preferred way - use Javaslang collections!
    return List.of(input).filter(...).map(...);
}

// import javaslang.collection.List;
java.util.List<T> compute(java.util.List<T> input) {
    // this is the preferred way to interoperate with Java
    return List.of(input).filter(...).map(...).toJavaList();
}

// import java.util.List;
List<T> compute(List<T> input) {
    // too long package name
    return javaslang.collection.List.of(input).filter(...).map(...).toJavaList();
}

// import java.util.List;
// import javaslang.collection._List;
List<T> compute(List<T> input) {
    // ugly prefix
    return _List.of(input).filter(...).map(...).toJavaList();
}

// import java.util.List;
// import javaslang.collection.SList;
List<T> compute(List<T> input) {
    // Aaahhhrg! HList would be a SHList
    return SList.of(input).filter(...).map(...).toJavaList();
}
```

`_` is currently the only prefix that does not make me jump out of the window but it is ugly though. I will stick with `List`.

**Comment by danieldietrich** [comment]
So...
classes in `javaslang.collection` are not intended to be used as `java.util.stream.Stream++`.
It is highly recommended to design programs or new parts of programs from the ground up to use immutable data structures. It is recommended to fully qualify java util collections, if used with javaslang collections side-by-side.

_When things should change we need to change s.th. otherwise nothing will change._

**Comment by nedtwigg** [comment]
Sounds good!  JavaSlang has lots of great ideas, I'm sure it will be successful no matter how you call them :)

In case you ever revisit this, [here](https://github.com/diffplug/durian-rx/tree/master/src/com/diffplug/common/rx) is an example of using prefixing to allow easy interoperability, and [here](http://blog.nedtwigg.diffplug.com/a-library-by-any-other-version) are more detailed thoughts on optimizing for conservative users versus the ones you already have.

**Comment by danieldietrich** [comment]
Thx!
