### ISSUE TITLE
Catching and throwing Throwable?

### ISSUE THREAD

**Issue by RobWin** [javaslang/javaslang#273]
Hello,

first of all. Thanks for this great library.

This is more a question than an issue.
Why do you throw and catch `Throwable` instead of `Exception`? For example in `Try`  or CheckedFunctionX? 
What is the purpose behind it? Fatal errors are anyway rethrown in the class `Failure`?

Kind regards,

Robert Winkler

**Comment by danieldietrich** [comment]
Hi,

thank you for the question!

For example, a StackOverflowError is considered ad recoverable (see [here](https://github.com/javaslang/javaslang/blob/master/src/main/java/javaslang/control/Failure.java#L211)).

It is interesting, that Scala considered StackOverflowError in 2.10.x as non-fatal (see [here](http://www.scala-lang.org/api/2.10.4/index.html#scala.util.control.NonFatal$)) and in 2.11.x as fatal (see [here](http://www.scala-lang.org/api/2.11.5/index.html#scala.util.control.NonFatal$)).

However, in general it would be too restrictive only considering Exception ad non-fatal. 3rd party frameworks may invent their own exceptions extending Throwable or may even throw Errors as recoverable exceptions (which is not recommended - but they do!).

I think, this is the best way to go but I'm always open for new ideas!!

Greets,

Daniel

**Comment by martin-g** [comment]
I agree with the reporter that catching Error/Throwable in library code
should be avoided.
If other libraries abuse the meaning of Error then it's their own problem.
I'd let the application decide whether to try to recover from
Error/CustomThrowable.

**Comment by jbgi** [comment]
So how about making a type parameter of the particular subtype of throwable
the function may throw?

**Comment by danieldietrich** [comment]
@martin-g 

> If other libraries abuse the meaning of Error then it's their own problem.

Yes, right. This is a violation of the contract of the `Error` class.

> I'd let the application decide whether to try to recover from Error/CustomThrowable.

This aligns well with the suggestion of @jbgi:

> So how about making a type parameter of the particular subtype of throwable the function may throw?

When composing multiple Try's, e.g. via flatMap, it is not possible for Java to calculate correct type bounds for the exception. This is especially the case because Throwable etc. are no interfaces (otherwise we could have used intersection types `X1 & X2`).

@jbgi: There are two problem with using a type parameter for the exception (see capitalized comments). Any ideas?

```java
@FunctionalInterface
interface CheckedSupplier<R, X extends Throwable> {
    R get() throws X;
}

@FunctionalInterface
interface CheckedRunnable<R, X extends Throwable> {
    void run() throws X;
}

public interface Try<T, X extends Throwable> {

    static <T, X extends Throwable> Try<T, X> of(CheckedSupplier<T, X> supplier) {
        try {
            return new Success<>(supplier.get());
        } catch (X t) { // <===== CANNOT CATCH TYPE PARAMETERS
            return new Failure<>(t);
        }
    }

    // INTERSECTION TYPE DOES NOT WORK =======v
    default <Y extends Exception> Try<Void, X & Y> andThen(CheckedRunnable<Y> runnable) {
        return flatMap(ignored -> Try.run(runnable));
    }
}
```

So, @RobWin, you made a good point with your question!

**Comment by danieldietrich** [comment]
I've slept one night over it and already had thoughts on it a year ago.

I think, we can't add a specific exceptions type because

* the type gets lost when chaining the first effect, e.g. `myTry.flatMap(e -> Try.of(() -> ...))`. `myTry` may be of `AException`. If the inner `Try.of` throws a `BException` we have two cases:
  1. `myTry` is a `Success`, then the whole result is a `Failure` of `BException`
  2. `myTry` is a `Failure`, then the whole result is a `Failure` of `AException`

* An `Error` may be non-fatal. For example it is common practice for servers to log such exceptions, i.e. `Try.of(() -> ...).onFailure(x -> LOG.ERROR("oh noes!", x)).map(e -> ...).get()`

* There may be a `HairyException extends Throwable`

A good practice would be to match the exception, as shown in the docs at http://javaslang.com:

```java
final A result = Try.of(this::bunchOfWork)
    .recover(Match
        .caze((Exception_1 e) -> ...)
        .caze((Exception_2 e) -> ...)
        .caze((Exception_n e) -> ...))
    .orElse(other);
```

Therefore I think, we will stay with `Throwable`.

**Comment by RobWin** [comment]
Ok. Thx for the explanation.

**Comment by danieldietrich** [comment]
@jbgi do you agree?

**Comment by jbgi** [comment]
@danieldietrich I think CheckFunction could be parametrized without Try taking advantage of it (still catching throwable).
also to address the original comment, maybe there could an alternate Try.of method that catch only non fatal exceptions (as per https://github.com/scala/scala/blob/2.12.x/src/library/scala/util/control/NonFatal.scala).

**Comment by danieldietrich** [comment]
@jbgi Thanks, that helped!

> I think CheckFunction could be parametrized without Try taking advantage of it

I will take a look at it...

> also to address the original comment, maybe there could an alternate Try.of method that catch only non fatal exceptions

This is already the default behavior. But looking at the code I think it can be optimized, e.g. throwing the original `Error` instead of the `Fatal` wrapper, if the exception if fatal.

```java
public interface Try {
    static <T> Try<T> of(CheckedSupplier<T> supplier) {
        try {
            return new Success<>(supplier.get());
        } catch (Throwable t) {
            return new Failure<>(t);
        }
    }
}

public class Failure<T> implements Try<T> {
    public Failure(Throwable t) {
        Objects.requireNonNull(t, "Throwable is null");
        final Cause cause = Cause.of(t);
        if (cause.isFatal()) {
            throw cause;
        } else {
            this.cause = (NonFatal) cause;
        }
    }
}

public static abstract class Cause extends RuntimeException {
    public static Cause of(Throwable t) {
        Objects.requireNonNull(t, "Throwable is null");
        if (t instanceof Cause) {
            return (Cause) t;
        }
        final boolean isFatal = (t instanceof VirtualMachineError && !(t instanceof StackOverflowError))
                || t instanceof ThreadDeath
                || t instanceof InterruptedException
                || t instanceof LinkageError;
        return isFatal ? new Fatal(t) : new NonFatal(t);
    }
}
```

**Comment by RobWin** [comment]
Yes. This looks better :)
