### ISSUE TITLE
Possible Lazy Stream issue evaluating additional value.

### ISSUE THREAD

**Issue by martincooper** [javaslang/javaslang#327]
Hi Daniel.

While doing some testing of the Javaslang lazy stream, I found a scenario where it looks like it evaluates an additional item to the last one requested. Implementing the same functionality in the core java Stream library I don't see this issue. The following replicates the scenario...

This code calls the doStuff method until it hits the first Failure case, then returns. As the doStuff method throws the exception when the value == 5, the println should only display "Doing 1" - "Doing 5"
whereas it actually also displays "Doing 6"

```java
    @Test
    public void one() {
        List<Integer> vals = List.of(1, 2, 3, 4, 5, 6, 7, 8, 9);
        Try<Void> test = flatTryOne(vals, this::doStuff);
    }

    private <T> Try<Void> flatTryOne(List<T> vals, Try.CheckedConsumer<T> func) {
        return vals.toStream()
                .map(v -> Try.run(() -> func.accept(v)))
                .findFirst(Try::isFailure)
                .orElseGet(() -> new Success<>(null));
    }

    private String doStuff(Integer i) throws Exception {
        System.out.println("Doing " + i);

        if (i == 5)
            throw new Exception("Some error !!!");

        return i + " Value";
    }
```

The same code using Java Stream functions as expected, with the last output being "Doing 5"

```java
    @Test
    public void two() {
        Integer[] vals = new Integer[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
        Try<Void> test = flatTryTwo(vals, this::doStuff);
    }

    private <T> Try<Void> flatTryTwo(Integer[] vals, Try.CheckedConsumer<Integer> func) {
        return java.util.stream.Stream.of(vals)
                .map(v -> Try.run(() -> func.accept(v)))
                .filter(Try::isFailure)
                .findFirst()
                .orElseGet(() -> new Success<>(null));
    }

    private String doStuff(Integer i) throws Exception {
        System.out.println("Doing " + i);

        if (i == 5)
            throw new Exception("Some error !!!");

        return i + " Value";
    }
```

I hope this explains sufficiently the issue.

**Comment by danieldietrich** [comment]
Hi Martin, thanks for the description - I will take a look now...

**Comment by danieldietrich** [comment]
In fact, the problem is the iterator().

A Stream is either a Cons(head, () -> tail) or Nil, where tail is also a Stream. In order to check whether the iterator has a next element, we have to check, if the tail Stream is a Cons or Nil. But when the iterator performs this check and tail is a Cons, the head of the tail Stream is evaluated.

To circumvent this we may wrap the head in a `Lazy<T>`. Then it will be evaluated only when head() is called. This would be the simplest solution but I have to think about it, if there is another solution which does not need an additional object...

**Comment by danieldietrich** [comment]
Btw - \*great\* finding!!

**Comment by martincooper** [comment]
:smiley: The finding was pure luck. A number of times i've needed a "mapUntilFailure" type method and wasn't sure if flatMap would work for this scenario. (From what I understand, flatMap would not stop when a Failure occurred, just removes them from the returned results?)

Implementing it manually and checking if it was really lazy by outputting to the console I came across this issue.

**Comment by danieldietrich** [comment]
> From what I understand, flatMap would not stop when a Failure occurred, just removes them from the returned results?

Yes, should be right

**Comment by danieldietrich** [comment]
A better explanation why Traversable.flatMap does filter out Failures:

It maps elements to Iterables and flattens all iterables to one Traversable in their order of occurrence. Collections and controls (Option, Try, ...) share the common interface Iterable. This is why Try instances can be flattenend to form a Traversable. In particular a Failure is empty because it contains no resulting value (but an exception that does not count as element).

**Comment by martincooper** [comment]
Thanks for the explanation. It makes sense.

**Comment by danieldietrich** [comment]
:+1:
