### ISSUE TITLE
Property Testing

### ISSUE THREAD

**Issue by sirinath** [javaslang/javaslang#474]
Can you use proofs to validate if they hold.

**Comment by danieldietrich** [comment]
Hi @sirinath,

thanks for the question. Currently not in the sense of [automated proof checking](https://en.m.wikipedia.org/wiki/Automated_proof_checking). Property checking here boils down to testing predicates on random generated test data. But theorems can be derived from polymorphic functions: http://ttic.uchicago.edu/~dreyer/course/papers/wadler.pdf

Do you think, there is room for improvement?

**Comment by danieldietrich** [comment]
_Automated proof checking_ and _property testing_ are two different things. The former is out of scope. The latter already tests if given _predicates_ can be satisfied.

I will close this ticket because I don't see how to further improve the property check framework. Next time, please give more details which features are needed in particular. Examples are welcome!
