### ISSUE TITLE
Create disjunction type

### ISSUE THREAD

**Issue by hamnis** [javaslang/javaslang#673]
A disjunction type similar to Scalaz \/ or Cats Xor type is useful. That is a right biased Either.

**Comment by danieldietrich** [comment]
Sounds nice! Have you a link for me to learn more about it?

**Comment by hamnis** [comment]
Some links to code.

https://github.com/scalaz/scalaz/blob/series/7.2.x/core/src/main/scala/scalaz/Either.scala

https://github.com/non/cats/blob/master/core/src/main/scala/cats/data/Xor.scala


Use would then be a just a normal monad.
example of `\/`
```scala
val c = for {
 a <- \/.right("hello")
 b <- \/.right("meh")
} yield { a + " " + b }

println(c)

// \/-("hello meh")
```

Left side operation will shortcut as expected. Use would be more `Option` like.

**Comment by danieldietrich** [comment]
Thx! An abstraction for Product would also make sense.

**Comment by danieldietrich** [comment]
See also http://www.scalactic.org/user_guide/OrAndEvery

**Comment by mvh77** [comment]
I've released Javactic 1.0.0-RC1 based on javaslang 2.0.0-RC2 (http://search.maven.org/#artifactdetails%7Ccom.github.javactic%7Cjavactic%7C1.0.0-RC1%7Cjar) Documentation here: http://javactic.github.io/javactic/

**Comment by talios** [comment]
@mvh77 +2! Looking nice.

**Comment by danieldietrich** [comment]
@mvh77 Yes, really nice. I'm looking forward to play around with it...

**Comment by danieldietrich** [comment]
This is obsolete because Either got a right-biased mode (see #882 and PR #1014).

See also [Fixing scala.Either - unbiased vs biased](http://robsscala.blogspot.co.uk/2012/06/fixing-scalaeither-unbiased-vs-biased.html) and [this Scala impl](https://github.com/robcd/scala-either-proj-map-returns-proj/tree/add_right-bias_2-10_withFilter).

I will close this for now. Please let me know if something is missing.
