### ISSUE TITLE
Adding folds that use Monoid

### ISSUE THREAD

**Issue by fredshonorio** [javaslang/javaslang#735]
Hello folks.
I think it would be useful to have folds in `Traversable<T>` that accept a `Monoid<T>`

A simple use case would be:
```java
public static Monoid<String> concat = new Monoid<String>() {
	public String combine(String a1, String a2) { return a1 + a2; }
	public String zero() { return ""; }
};
...
Stream.of("1", "2", "3").foldLeft(concat);
```
which would produce `"123"`.

**Comment by danieldietrich** [comment]
Hi, thx - great suggestion!

Sorry for the late answer. I just realized that I didn't watch my own project any more o_O and therefore received no notifications. Fixed that.

**Comment by danieldietrich** [comment]
I removed the algebra package in 2.0.0. It might be re-added in 2.0.1... I have to further investigate how to tightly integrate Monads. Currently Traversables behave semi-monadic with a `flatMap(Function<T, Iterable>)`

**Comment by fredshonorio** [comment]
Ah, I haven't tried 2.0 yet. Any particular reason to remove the package?

**Comment by danieldietrich** [comment]
I thought of having algebraic operations in a separate, pure abstraction layer. For that reason we wanted to create [`javaslang-pure`](https://github.com/javaslang/javaslang/milestones/javaslang-pure).

There where some caveats regarding Java's type system. I had to make some design decisions in order to make the code more readable. One example is the need for higher-kinded types. I created a type `Kind<M, A>` which was used for constructing types. But I think for most users it is more confusing than helping.

I ask myself if we are able to _lift_ the algebraic types to an _abstract, compositional_ layer which acts upon the core Javaslang layer.

Here are some issues regarding this topic:

* #288 Add substitute for removed Monad interface
* #300 [Analysis] How to add a Monad abstraction on top of existing monadic classes

In our example, we may have

```java
interface Monoid<T> {
    <M extends Traversable<T>> T fold(M that) {
        that.fold(zero(), this::combine);
    }
}
```

**Comment by danieldietrich** [comment]
See also #674 for folds (https://github.com/javaslang/javaslang/issues/674#issuecomment-153706017)

I will check if and how to re-add the `javaslang.algebra` package to Javaslang.

Because of the lack of higher-kinded types we needed to fall back to

```java
interface FilterMonadic<T> {

   <U> FilterMonadic<U> flatMap(Function<? super T, ? extends java.lang.Iterable<? extends U>> mapper);

    // ...

}
```

A _real_ monadic type would have instead:

```java
<U> Monad<U> flatMap(Function<? super T, ? extends Monad<? extends U>> mapper);
```

But that is not possible with Java. I created `Kind<M extends Kind<M, ?>, T>` to separate the container type `M` from its component type `T`. This allowed us to write

```java
// think it looked like this not 100% sure - but the idea counts
interface Monad<M extends Monad<M, ?>, T> extends Kind<M, T> {
    <U, MONAD extends Kind<M, U>> MONAD flatMap(Function<? super T, ? extends MONAD> mapper);
}

interface List<T> extends Monad<List<?>, T> {
    @Override
    <U, LIST extends Kind<List<?>, U>> List<U> flatMap(Function<? super T, ? extends LIST> mapper);
}
```

I think for most programmers the current type signatures fit better:

```java
interface List<T> {
    <U> List<U> flatMap(Function<? super T, ? extends Iterable<? extends U>> mapper);
}
```

Have to think about it again, how to integrate the algebraic interfaces (Monad, Functor, Monoid, ..., maybe here also Foldable, ...)

**Comment by danieldietrich** [comment]
Here is the last version that included the `javaslang.algebra` package: [87ea020354](https://github.com/danieldietrich/javaslang/tree/87ea0203544a5de1f9a39e1a4caee67d3f5e3533).

I will now pull it out of the grave and re-animate it.

Plan:

```java
@FunctionalInterface
interface Semigroup<A> {

    A combine(A a1, A a2);
}

interface Monoid<A> extends Semigroup<A> {

    static <A> Monoid<A> of(A zero, Semigroup<A> semigroup) { ... }

    static <A> Monoid<Function<A, A>> endoMonoid() { ... }

    A zero();
}
    
interface Foldable<T> extends java.lang.Iterable<T> {

    // convenience method, same as foldLeft(monoid)
    T fold(Monoid<? extends T> monoid);

    T fold(T zero, BiFunction<? super T, ? super T, ? extends T> combine);

    T foldLeft(Monoid<? extends T> monoid);

    <U> U foldLeft(U zero, BiFunction<? super U, ? super T, ? extends U> combine);

    T foldRight(Monoid<? extends T> monoid);

    <U> U foldRight(U zero, BiFunction<? super T, ? super U, ? extends U> combine);
}

interface Functor<T> {

    <U> Functor<U> map(Function<? super T, ? extends U> mapper);
}

// this is more like a relaxed monad / semi monad / filter monadic
interface Monad<T> extends Functor<T> {

    Monad<T> filter(Predicate<? super T> predicate);

    <U> Monad<U> flatten();

    <U> Monad<U> flatMap(Function<? super T, ? extends java.lang.Iterable<? extends U>> mapper);

    @Override
    <U> Monad<U> map(Function<? super T, ? extends U> mapper);
}
```

* `Kind`, `CheckedFunctor` and `CheckedMonad` are not needed any more.
* collections (`TraversableOnce`) and controls (`Option`, `Try`, etc.) will implement `Monad` and `Foldable`)

**Comment by jbgi** [comment]
@danieldietrich I spent some times recently on how best implement Semigroup/Monoid in Java. Result have been merged into fugue, if you want to have a look: https://bitbucket.org/atlassian/fugue/pull-requests/51/fixed-37-semigroups-and-monoids/diff

**Comment by danieldietrich** [comment]
@jbgi awesome, thx!

**Comment by danieldietrich** [comment]
@jbgi do you have a `foldMap`?

```java
/**
 * Maps this elements to a {@code Monoid} and applies {@code foldLeft}, starting with {@code monoid.zero()}:
 * <pre><code>
*  foldLeft(monoid.zero(), (ys, x) -&gt; monoid.combine(ys, mapper.apply(x)));
 * </code></pre>
 *
 * @param monoid A Monoid
 * @param mapper A mapper
 * @param <U>    Component type of the given monoid.
 * @return the folded monoid value.
 * @throws NullPointerException if {@code monoid} or {@code mapper} is null
 */
default <U> U foldMap(Monoid<U> monoid, Function<? super T, ? extends U> mapper) {
    Objects.requireNonNull(monoid, "monoid is null");
    Objects.requireNonNull(mapper, "mapper is null");
    return foldLeft(monoid.zero(), (ys, x) -> monoid.combine(ys, mapper.apply(x)));
}
```

**Comment by jbgi** [comment]
yeah. It should be on Foldable (or Fold using lenses): https://github.com/functionaljava/functionaljava/blob/master/core/src/main/java/fj/data/optic/Fold.java#L26

**Comment by danieldietrich** [comment]
Our semi-`Monad` types will obey the following monad laws:

* Right identity: `m.flatMap(unit) ≡ m`
* Associativity: `m.flatMap(f).flatMap(g) ≡ m.flatMap(x -> f.apply(x).flatMap(g))`

Because the `mapper` function of `flatMap` returns an `Iterable` type instead of a `Monad`, the following monad law ~~does~~ may only hold (depending of the concrete implementation), if our `Monad` interface is also of type `Iterable`:

* Left identity: `unit(a).flatMap(f) ≡ f.apply(a)`

However, we will not make the `Monad` interface extend `Iterable` because this is not very _algebraic_.
