### ISSUE TITLE
Consider splitting up the library in more jars

### ISSUE THREAD

**Issue by hamnis** [javaslang/javaslang#748]
It could be beneficial to split up the library in more parts, so one might pick the parts that is needed for the project at hand and not having to depend on an increasingly bigger library.

Suggestions for modules can be:

* base
* collections
* concurrent

**Comment by danieldietrich** [comment]
Hi,

in general this is a good idea. However, at the moment the additional overhead would be too much compared to the benefits. E.g. `javaslang.concurrent` does only contain 2 classes.

Also I'm in fear of _versioning hell_ :-)

At the moment Javaslang is nice and lean. I think it has a good size.

Daniel

**Comment by hamnis** [comment]
Hi Daniel.

As long as the library modules are contained within one git project, convention dictates that all modules are versioned the same.

You might also distribute an "all" jar that contains everything, then users can pick and choose.

Doing this early might help with adoption, at least for my own part. It can potentially also showcase dependency problems between classes, if there are any.

**Comment by danieldietrich** [comment]
The (intra-)integration aspect is an integral aspect of Javaslang. The current lib represents _the core_, with all aspects we have so far!

### Base (package: `javaslang`):

The base contains the following at its _core_:

* Function*
* Tuple*
* Lazy

These are base interfaces which encapsulate functionality wich needs to be kept in one place (_high cohesion_ of functionality):

* Iterable (note: similar to `java.lang.Iterable`'s Iterator resides in `java.util`, Javaslang's Iterator also resides in a different package, namely `javaslang.collection.Iterator`)
* Value (note: literally all Javaslang types but Tuple* and Function* are of type Value. Therefore here reside the conversion methods between Values and therefore we have dependencies to _all_ packages)

### Vision

Javaslang is being developed with focus on a high level of intra-interoperability. All 'just fits together'.

**This is exactly the part which makes developing fun. It 'just works'.**

```java
// = Some(hi)
Option<String> option = Option.of("hi");

// = List(hi)
List<String> list = option.toList();
```

or

```java
// = List()
List<String> list = list.empty();

// = Failure(java.util.NoSuchElementException)
Try<String> try = list.toTry();

// but... = Success(hi)
List.of("hi").toTry()
```

### Compositional Programming

I could also imagine to integrate Future - and therefore concurrency - more tightly into the collection library:

```java
Future<Seq<String>> someFutureResult = Stream.of(1, 2, 3, 4)
        .parallel()
        .map(someMapping)
        .filter(someFiltering);
```

an implementation could look like this:

```java
// just an example - can be easily generalized
Stream<Future<String>> stream = Stream.of(1, 2, 3, 4)
        .map(i -> Future.of(() -> {
            Thread.sleep(rnd.nextInt(250));
            return String.valueOf(i);
        }));

Future<Seq<String>> sequence = Future.sequence(stream);
// ...
```

this would need `parallel()` return something like

```java
// note: maybe Future then cannot be a value in order not to clash with Seq
interface ParrallelSeq<T> extends Future<Seq<T>>, Seq<T> {

    // ...

}
```

Do you see the benefits?

**Comment by danieldietrich** [comment]
Of cause each type could have a static `convert(Value)` method instead to the conversion methods `Value.toXxx()`. This would decouple _some_ of the existing dependencies.

```java
// = list.toOption()
Option.convert(list);
```

In general, the end-user does not see the dependencies directly. It's all a matter of decoupling a system for the reason of making things exchangeable. But Javaslang is more like a _language extension_ for Java it does not really need to be decoupled at its core.

On the other hand - when having mobile development in mind, it might be interesting to have minimal modules because of limited amount of memory. However, the Android platform currently does not support Java 8 and iPhone development with Java is also still in its infancy. However, I've heard that in (in near) future, Java will run natively on iPhone. Maybe a modularized Javaslang is a target for a future Javaslang release (3.0.0?), also when having Java 9/Jigsaw at hand...

Btw, we will have additional modules for interoperability with _other libs_, like the new [javaslang-jackson](https://github.com/javaslang/javaslang-jackson) module.

**Comment by danieldietrich** [comment]
In fact, more abstract composability would be the solution for better modularity. But I don't know if this would the library more usable for most of the users. This would go more in the direction of [functionaljava](https://github.com/functionaljava/functionaljava/tree/master/core/src/main/java/fj). Did you take a look at it already? However, I think it also isn't modularized...

**Comment by danieldietrich** [comment]
Note to myself: with #716 this will be possible:

```java
Stream.from(1)                                   // Stream(1, 2, 3, ...)
        .map(i -> Future.of(() -> getPerson(i))) // Stream(Future<Person>, Future<Person>, ...)
        .transform(Future::sequence)             // Future<Seq<Person>>
``

**Comment by danieldietrich** [comment]
@hamnis: Please provide me with the following information which will help me to slice modules:

* What are the main features you are interested in?
* Which Javaslang features are currently out of focus for you?
* Which other libs do you use for features which Javaslang offers?

Many thanks!

Greets

Daniel

**Comment by danieldietrich** [comment]
The Property Checking framework in `javaslang.test` is a good candidate to move to a different module, let's say `javaslang-test`.

**Comment by hamnis** [comment]
When I say modularization i just mean Jar files. Optional Dependencies which I may pick and choose what I need from. A project may have as many jar files it wants, even if a jar file only contains one class.

Sometimes i just have to write the thing I need where I need it, since adding a increasingly bigger library doesn't really benefit my users if I only need one class or method.

The Value thing is sometimes useful, I see that.This seems like just a way to avoid having to repeat yourself, which is of course a noble goal. If it, however, introduces a dependency which is not really needed, then maybe not keeping it DRY is better. Your milage may vary.

The property checking framework should probably be in its own git project with its own release cycle.

Functional Java is also not modularized in this fashion, and is one of my main problems with it.

**Comment by hamnis** [comment]
As a side note I am becoming more and more fan of a more `typeclass based` design. Keeping things DRY, but having code that relates to the class outside the class if's only useful sometimes.

**Comment by danieldietrich** [comment]
I will start modularization after the release of 2.0.0 (on 1st Dec).

At a minimum `javaslang.test` will move to its own repo.

Additionally it will be investigated how to reduce dependencies to slice Javaslang.

Build: it could be a multi-module maven project with several jars etc.

**Comment by danieldietrich** [comment]
We will make a separate `javaslang-test` module starting with 2.0.0. Gen, Arbitrary, Property et al. will move to `javaslang-test`. The `javaslang` 2.0.0 release will then look like this. 

![javaslang-2 0 0-rc2](https://cloud.githubusercontent.com/assets/743833/11325874/dc0b4b32-9159-11e5-97a4-e876477dc449.png)

Gen and Arbitrary currently implement Value. I will re-think this.

**Comment by danieldietrich** [comment]
I understand Javaslang as language extension.

> It replaces "a well-known conventional synonym". This is done primarily to avoid discomfort caused by the conventional synonym or discomfort or annoyance caused by having to elaborate further.

_See [wikipedia/Slang](https://en.wikipedia.org/wiki/Slang)._

Not all people will love it.

> "It's a taboo term in ordinary discourse with people of a higher social status or greater responsibility."

But that's ok. Important is its purpose. We have a clear vision - more control, less code.

> Slang is on the edge.

The whole is more than the sum of its parts. Therefore providing a set of separate fragments was not the original idea when creating Javaslang.

However, the Java standard library is modularized by itself. Maybe we will do the same to enable mobile platforms to use it. But maybe future mobile platforms will not have resource problems any more because of future enhancements of processors and memory.

**Comment by danieldietrich** [comment]
This will take place after 2.0.0 - too much technical overhead without any business value...

**Comment by danieldietrich** [comment]
We defined separate modules

- javaslang
- javaslang-match
- javaslang-pure
- javaslang test

These are the core Javaslang components and are shipped in separate jars. Other components can be found in separate Javaslang. projects.

We can't split up the core project 'javaslang' into more fine-grained packages because it contains basic building blocks which rely on each other.

Thank you for suggesting to split the project.
