### ISSUE TITLE
Static constructor .of() on all control classes

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#889]
To be consistent with collections and Scala's apply methods, we should have static .of() on all classes in the control package as well, including:
- Success.of()
- Failure.of()
- Left.of()
- Right.of()
- Some.of() => Some.of(null) should return a Some with a null in it to be consistent with Scala. All of the above too I guess, to verify!
- ~~None.instance()? or maybe Option.none() is enough for this one.~~ Already there

**Comment by mvh77** [comment]
So how close to Scala do we want to be on these things concerning nulls? I notice that currently the constructors do null checks, but Scala doesn't disallow null. Here's what the worksheet says:
```scala
val fail  = Failure(null)    //> fail  : scala.util.Failure[Nothing] = Failure(null)
val succ  = Success(null)    //> succ  : scala.util.Success[Null] = Success(null)
val try_  = Try(null)        //> try_  : scala.util.Try[Null] = Success(null)
 
val some   = Some(null)      //> some  : Some[Null] = Some(null)
val option = Option(null)    //> option  : Option[Null] = None
 
val left  = Left(null)       //> left  : scala.util.Left[Null,Nothing] = Left(null)
val right = Right(null)      //> right  : scala.util.Right[Nothing,Null] = Right(null)
```
Notice that Try(null) becomes Success(null) but Option(null) becomes None.

**Comment by ruslansennov** [comment]
:+1:

**Comment by danieldietrich** [comment]
Hi Martti, thank you for this great investigation!

we will add the additional static factory methods `of` to the other types for convenience. They will be pretty much like Scala's companion object methods.

I was not aware of this null-handling. We have to be careful in Javaslang not to break something, for example the Failure.NonFatal.equals method currently relies on the fact the the exception is not null.

**Comment by enelson** [comment]
@danieldietrich I'd love to tackle another task if you're okay with it. I could take this one on if someone hasn't already started it.

**Comment by danieldietrich** [comment]
@enelson That would be awesome - but I think the target moved here because we moved the impl classes into the interfaces, e.g. Option.Some, Option.None, Try.Success, etc.

The constructors are now private and we added factory methods to the interfaces, e.g. Option.some(T), Option.none(), Try.success(...), etc.

Given that I think we can close this ticket now.

**Comment by enelson** [comment]
No worries, thanks. Any other 2.0.0 task I could help with? I've been enjoying using this library and love to contribute to it. Or I could help on 2.0.1 also. You know what needs help. Thanks @danieldietrich.

**Comment by danieldietrich** [comment]
@enelson You could take a look at "Add sequence methods" #767. This one turns a sequence of monad instances inside out. E.g.

A sequence of futures `Future.sequence(Future<T1>, ..., Future<Tn>)` is turned into a future of sequential results `Future<Seq<T1, ..., Tn>`.

This is non-trivial because the characteristics of the Monad are reflected by the static sequence method.

I already added Future.sequence and Lazy.sequence. I don't think we need the sequence method for collections. We need to implement the sequence method for controls. These are:

* Either - here we have two Monads: LeftProjection and RightProjection. I don't know yet how to proceed here. Maybe it makes more sense to add the sequence method to Either instead. Please take also a look if and how Scala does it (also scalaz).
* MatchMonad - a sequence of MatchMonad's is turned into a MatchMonad of Seq of values. The resulting MatchMonad isEmpty() if at least one of the input MatchMonad's does not match.
* Option - the result is none if at least one of the options is none
* Try - should be very similar to Future because we also have failures. The result is a failure if at least one of the Try's fails
