### ISSUE TITLE
lastIndexOf seems buggy

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#903]
Scala:
```scala
val vec = Vector(1,2,3,1,2,3)    //> vec  : scala.collection.immutable.Vector[Int] = Vector(1, 2, 3, 1, 2, 3)
val vec2 = Vector(1,2,3)         //> vec2  : scala.collection.immutable.Vector[Int] = Vector(1, 2, 3)
vec.lastIndexOfSlice(vec2)       //> res5: Int = 3
vec.lastIndexOfSlice(vec2, 2)    //> res6: Int = 0
```
Javaslang:
```java
Vector<Integer> vec = Vector.of(1,2,3,1,2,3);
Vector<Integer> vec2 = Vector.of(1,2,3);
vec.lastIndexOfSlice(vec2);      // 3
vec.lastIndexOfSlice(vec2, 2);   // 3

```

**Comment by danieldietrich** [comment]
Hi Martti, thank you for your finding!

Btw - Great project [javactic](https://github.com/javactic/javactic)

**Comment by mvh77** [comment]
Thanks! Official release Javactic once Javaslang 2 is out!

**Comment by RobWin** [comment]
Why not add it as a Javaslang-module?

**Comment by mvh77** [comment]
What does that mean technically?

**Comment by RobWin** [comment]
If @danieldietrich agrees, we could move the project into the javaslang organisation and add you as a team member to a group which can mantain the javaslang-javatic repo.

**Comment by danieldietrich** [comment]
Generally a good idea!

My vision is the following:

Projects asked for from the outside, like adapters for existing, popular frameworks, should be included. It helps people to integrate Javaslang in their environments. javaslang-jackson is an example for supporting JSON marshalling/unmarshalling.

In order to include projects we should wait a while until they emerged from the incubation phase.

Please do not underestimate the maintenance factor for a project. It would be no good marketing strategy to have an organization where many projects are not maintained any more.

So for now I added...

# [awesome-javaslang](https://github.com/javaslang/awesome-javaslang)

to create a list of awesome Javaslang projects. **Please add your projects!**

@ruslansennov I added javaslang-jackson. It would be great to have to minimal code snippets/examples for searialization/deserialization (e.g. of a List.of(1, 2, 3) or something simple)

/cc @ggalmazor (jfry), @RobWin (circuit-breaker), @mvh77 (javactic)
