### ISSUE TITLE
Are container types purposefully desined to be like Java's Optional or should they be more like Scala's?

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#909]
In Scala a container C\[T\] (like Option or Try) will have:
- get that returns a T
- getOrElse that returns a U (with U >: T)
- orElse that returns a C\[U\] (with U >: T)
- recover that returns a C\[U\] taking a function E => U (with E a secondary type like Throwable in Try)
- recoverWith that return a C\[U\] taking a function E => C\[U\]

but we have (and this seems to come from Java's Optional :scream:):
- get that returns a T
- orElse that returns a T :warning: 
- orElseGet (taking a Supplier) that also returns a T :warning: 
- recover => like Scala
- recoverWith => like in Scala.

Can this be refactored, with eager and lazy versions of getOrElse and orElse that are consistent with Scala? The rule seems to be that anything starting with *get* returns the contain**ed** type, anything starting with *orElse* returns the contain**er** type and anything starting with *recover* also returns the container type but gets a function from the alternative type.

**Comment by danieldietrich** [comment]
Caution! Scala's type system behaves completely different than Java's.

**Example 1:** `orElse`

We have `T orElse(T other)` which allows us to do this:

```java
Number n = 3d;
Option<Number> option = Option.of(n);
Number number = option.orElse(new BigDecimal("0"));
```

In other words we don't need to declare it as:

```java
<U extends T> T orElse(U other);
```

**Example 2:** `orElseGet`

Also here we have nothing to do because

```java
T orElseGet(Supplier<? extends T> supplier);
```

should be equivalent to

```java
<U extends T> T orElseGet(Supplier<U> supplier);
```

**Comment by danieldietrich** [comment]
Yes, good catch. We will refactor it to be consistent with Scala.

**Comment by mvh77** [comment]
Yes, I was talking more about method naming than variance things, sorry for mixing that in there. So I would have this (on Try for example), would this fulfill all use cases?
```java
    T      get();
    T      getOrElse(T def);
    T      getOrElse(Supplier<? extends T> def);
    Try<T> orElse(Try<? extends T> alt);
    Try<T> orElse(Supplier<? extends Try<? extends T>> alt);
    Try<T> recover(Function<? super Throwable, ? extends T> func);
<U> Try<T> recoverWith(Function<? super Throwable, ? extends Try<U>> func);
```
and so the functionality from the current orElseGet(Function<? super Throwable, ? extends T> other) can be gotten with a call to recover(...).get(). I'm not familiar enough with the use cases for orElseRun,  orElseThrow and orElseTry to know if these are really useful.

**Comment by danieldietrich** [comment]
Thank you Martti! This looks good to me. I will perform the refactoring if you don't mind to ensure all use cases still hold. Maybe I have to remove functionality.

**Comment by mvh77** [comment]
Sure go ahead! I really like it how you are open to suggestions, very easy to work with! :smile: I would maybe remove orElseRun, orElseThrow and orElseTry for now unless you come up with good names for them. They can always be added later on, but renaming/removing them once they are there is more difficult. The methods above are the ones I have in Or in Javactic right now. :wink:  http://javactic.github.io/javactic/javadoc/

**Comment by danieldietrich** [comment]
Thx :) Sometimes I need some hours/days to get a distant view of my own API and take suggestions into account.

Good hint to re-visit the methods orElseRun, orElseThrow and orElseTry. I will do that.

**Comment by mvh77** [comment]
as they are terminal operations, maybe just orRun, orThrow, orTry?

**Comment by mvh77** [comment]
sorry, only orElseRun is terminal...

**Comment by danieldietrich** [comment]
```java
// instead of the 'old' orElseRun we use this existing methods:
Try<T> onFailure(Consumer<? extends Throwable> action);

// orElseThrow is the same as but the exception is wrapped in a NonFatal
recover(...).get();
```

We added `Value.orElseTry` as syntactic sugar on Nov 25: https://github.com/javaslang/javaslang/issues/851

I think instead we may use:

```java
value.toTry().getOrElse(supplier);
```

**Comment by danieldietrich** [comment]
Phase 1: I've refactored the following methods:

```java
get( )                        (ok, no changes)
getOption()                   (ok, no changes)
orElse(T)                  -> getOrElse(T)
orElseGet(Supplier)        -> getOrElse(Supplier)
orElseGet(Function)        -> getOrElse(Function)
orElseTry(CheckedSupplier) -> getOrElseTry(CheckedSupplier)
orElseThrow(Function)      -> getOrElseThrow(Function)
orElseRun                     (ok, no changes)
recover(Function)             (ok, no changes)
recoverWith(Function)         (ok, no changes)
```

In Phase 2 I will create the missing methods:

```java
Value<T> orElse(Value<? extends T> alt);
Try<T> orElse(Supplier<? extends Try<? extends T>> alt);
```

Also we need to synchronize these methods on Try, Future and maybe Either.

**Comment by danieldietrich** [comment]
Scala has the method `orNull` that works similar to `getOrElse(null)`:

```scala
def orNull[A1 >: A](implicit ev: Null <:< A1): A1 = this getOrElse ev(null)
```

Examples:

```scala
//> res0: Null = null
None.orNull

//> res1: String = A
Some("A").orNull

// Errors:
// - Cannot prove that Null <:< Int.
// - not enough arguments for method orNull: (implicit ev: <:<[Null,Int])Int. Unspecified value parameter ev.
Some(1).orNull
```

I think in our context the name is misleading. It should have been `getOrNull` because the contained value is returned. However, I think we will not support it. If null is needed we have to type the longer version `getOrElse(null)`.

/cc @mvh77

**Comment by danieldietrich** [comment]
`orElse` cannot be added to our base-class `Value`, because the alternate value is of the current self-type:

```java
interface Option<T> {
    Option<T> orElse(Option<? extends T> alternate);
    Option<T> orElse(Supplier<? extends Option<? extends T>> alternate);
}
```

Therefore all single-valued types, i.e. controls and Future, will have a signature with their own type (as shown above for Option).

We could also provide this method for Traversables, why not?

```java
interface Traversable<T> {
    Traversable<T> orElse(Iterable<? extends T> alternate);
    Traversable<T> orElse(Supplier<? extends Iterable<? extends T>> alternate);
}

interface List<T> {
    @Override
    List<T> orElse(Iterable<? extends T> alternate);
    @Override
    List<T> orElse(Supplier<? extends Iterable<? extends T>> alternate);
}
```

etc.

**Comment by mvh77** [comment]
Yes you're right, that orNull is inconsistent in Scala, but getOrElse(null) should be enough for the very rare cases where you want a null out.

**Comment by danieldietrich** [comment]
Yep, ok

**Comment by danieldietrich** [comment]
Another approach implementing orElse would be to let it look like

```java
interface Value<T> {
    Value<U> flatMap(Function<T, Iterable<U> f);
}
```

where flatMap is defined as `unit(map(f).flatten())`. The `unit` function is some kind of selector which closes the world between single-valued and multi-valued types. We need it because Java has no higher-kinded types, otherwise we could not define a common flatMap method.

In other words we would define orElse like this:

```java
interface Value<T> {
    Value<T> orElse(Iterable<? extends T> alternate);
    Value<T> orElse(Supplier<? extends Iterable<? extends T>> alternate);
}
```

In the else case we would internally alternate, if it is of the right type, or convert it to the return type of orElse.

**Comment by mvh77** [comment]
Personally I like your first approach better with the more specific types.

**Comment by danieldietrich** [comment]
Yes, that's the way we will go. See also #1044

**Comment by danieldietrich** [comment]
@ruslansennov could you add these to Values (but not to Traversables!)

Example for Try:

```java
interface Try {
    Try<T> orElse(Try<? extends T> alt);
    Try<T> orElse(Supplier<? extends Try<? extends T>> alt);
}
```

Because the type (here: Try) is part of the method arguments and Java has no higher-order types, we need to add the function not to all classes. This is the list which has the methods:

* Either, LeftProjection, RightProjection
* Future
* Lazy
* MatchMonad
* Option
* Try
* Validation

Thank you!

**Comment by ruslansennov** [comment]
sure

**Comment by danieldietrich** [comment]
Ruslan finished it!

**Comment by ggalmazor** [comment]
Hi all!

I'm migrating a large codebase from Javaslang 1.2 to version 2.1.x and we use extensively `o.orElse(null)` that would have to be migrated to `o.getOrElse(null)`. 

Let me explain beforehand that we only do this in our domain boundaries when interacting with third party libraries that require nulls to work properly.

The problem is that the compiler can't decide which implementation of `getOrElse()` to use because there are two of them (one with a `T other` and another one with `Supplier<? extends T> supplier`). The solution at this moment is to do a weird cast of null: `o.getOrElse((T) null)`.

A method `o.getOrNull()`  would be very helpful to produce a less verbose code. As discussed on this thread, I wouldn't use scala's `orNull` syntax to be more coherent with Javaslang's current API.

**Comment by danieldietrich** [comment]
Hi Guillermo,

getOrNull() sounds reasonable. Could you add an issue please? A default method in the Value interface will do the job:

```java
interface Value<T> {
    default T gerOrNull() {
        return isEmpty() ? null : get();
    }
}
```

Thx!
